# Generated by Django 4.2.20 on 2025-03-19 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.CharField(choices=[('GREEN', 'Green'), ('RIPENING', 'Ripening'), ('RIPE', 'Ripe'), ('OVERRIPE', 'Overripe')], max_length=8)),
                ('read', models.DateTimeField(auto_now_add=True)),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fruit')),
            ],
        ),
    ]
