# Generated by Django 4.2.20 on 2025-03-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitreading',
            name='reading',
            field=models.CharField(choices=[('GREEN', 'Verde'), ('RIPENING', 'Amadurecendo'), ('RIPE', 'Madura'), ('OVERRIPE', 'Passada')], max_length=8),
        ),
    ]
